### ISSUE TITLE
PEP8 fixes ?

### ISSUE THREAD

**Issue by thefab** [andreasjansson/envtpl#16]
Interested in PEP8 fixes and a little "Makefile" to test that ?

flake8 tool reports 63 issues (mainly about too long lines)

**Comment by andreasjansson** [comment]
If you have time that'd be very useful! I'd probably bump the line length limit up to 100 or maybe even 120 (or `current_year - 1900` :smile: )

**Comment by andreasjansson** [comment]
fixed by https://github.com/andreasjansson/envtpl/pull/17
