### ISSUE TITLE
Importing envtpl 0.5.2 breaks stdout and stderr on python3

### ISSUE THREAD

**Issue by ikseek** [andreasjansson/envtpl#19]
envtpl module wraps sys.stdout and sys.stderr with streamwriter which outputs bytes.
And in python3.5.1 sys.stdout and sys.stderr are in text mode by default and raise TypeError if you try to write() bytes in it.
See https://docs.python.org/3.5/library/sys.html#sys.stderr

**Comment by andreasjansson** [comment]
Thanks for reporting this, and sorry it's taken so long to fix. I just pushed 0.5.3 (https://github.com/andreasjansson/envtpl/commit/6d356d85d3d4f39dbc7fe5f99f317fc326d92fca) with fixes. Would you mind testing again and see if it worked?

**Comment by ikseek** [comment]
Tested, works fine, thanks!
