### ISSUE TITLE
Provide a way to use template inheritance with envtpl

### ISSUE THREAD

**Issue by thefab** [andreasjansson/envtpl#21]
With the first example (base.html, child.html) at this url:
http://jinja.pocoo.org/docs/2.9/templates/#template-inheritance

I would like to be able to use:
cat child.html |envtpl >out.html
(if base.html is in the same directory than child.html)

I got "Error: base.html"

**Comment by thefab** [comment]
Note that it works without using standard input/outputs. But I like using envtpl as a kind of "unix filter".

This patch seems to fix this issue:

```
diff -up envtpl-0.5.3/envtpl.py.orig envtpl-0.5.3/envtpl.py
--- envtpl-0.5.3/envtpl.py.orig	2017-04-06 12:55:31.544919085 +0200
+++ envtpl-0.5.3/envtpl.py	2017-04-06 12:56:25.040225212 +0200
@@ -96,7 +96,9 @@ def process_file(input_filename, output_
 
 def _render_string(string, variables, undefined):
     template_name = 'template_name'
-    loader = jinja2.DictLoader({template_name: _unicodify(string)})
+    loader1 = jinja2.DictLoader({template_name: _unicodify(string)})
+    loader2 = jinja2.FileSystemLoader(os.getcwd())
+    loader = jinja2.ChoiceLoader([loader1, loader2])
     return _render(template_name, loader, variables, undefined)
```

If you are interested in, I can provide a pull requests with tests.

**Comment by andreasjansson** [comment]
@thefab sorry for digging up old issues, trying to be a better maintainer... This was fixed in https://github.com/thefab/envtpl/commit/6d2285c8a85dd988f109de645a977742fe5c9cfe right? If not, please reopen.

**Comment by thefab** [comment]
yes fixed for me but not in your upstream branch

Some interesting things in my branch : 
https://github.com/andreasjansson/envtpl/compare/master...thefab:master

If you are interested in some of these (little) changes, please ping me, I will open some PR
