### ISSUE TITLE
New PyPi release (Python 3 compatible)

### ISSUE THREAD

**Issue by jstaffans** [andreasjansson/envtpl#8]
The latest version on PyPi (0.3.2) doesn't seem to contain the fixes for Python 3+ that were merged to master (see https://github.com/andreasjansson/envtpl/issues/3)

**Comment by andreasjansson** [comment]
Thanks, I must have forgot to upload. [0.4.1](https://pypi.python.org/pypi/envtpl/0.4.1) is on pypi now.
